### PR TITLE
Upgrade tiller command

### PR DESCRIPTION
**Pull request by sabbour**
ACS Engine provisioned cluster already had Helm installed (message below)

```
helm init --service-account tiller
$HELM_HOME has been configured at /Users/sabbour/.helm.
Warning: Tiller is already installed in the cluster.
```

However, the tiller installed was an older version

```
helm install svc-cat/catalog --name catalog --namespace catalog
Error: incompatible versions client[v2.7.2] server[v2.6.2]
```

Proposed solution is to upgrade tiller by running:

```
helm init --upgrade
```

### CODE REVIEW

**Comment by jeremyrickard** [comment]
Hey @sabbour, thanks for catching that issue and the PR! I'm wondering if it might be better to make a note in that section indicating that you need to upgrade tiller if using ACS, as it's not necessary for AKS or Minikube deployments.  We have several Note: ....blocks in the OSBA [quick start](https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-minikube.md).  @krancour thoughts?

**Comment by sabbour** [comment]
Thanks @jeremyrickard.

I thought AKS wasn't supported yet?
Actually I haven't been able to get it to work on an ACS Engine provisioned cluster so far (v.0.10.0).

It seems some cluster roles are missing (cluster-admin). I've created it but I'm getting other errors.

I'll update this comment with the error in a few hours as I'm not sure if it is coming from this project.

**Comment by jeremyrickard** [comment]
@sabbour I believe we're supporting AKS, check out the following doc:

https://docs.microsoft.com/en-us/azure/aks/integrate-azure

For AKS, note you need to disable RBAC when installing service catalog:
>helm install svc-cat/catalog --name catalog --namespace catalog --set rbacEnable=false

**Comment by sabbour** [comment]
@jeremyrickard [This](https://github.com/Azure/helm-charts/blob/master/docs/prerequisities/README.md) says otherwise regarding AKS support.

> Currently, AKS does not support aggregated APIs, which are required for service-catalog installation. Support is forthcoming, and this document will be updated when aggregated APIs are supported.

Should we update it?

**Comment by jeremyrickard** [comment]
@sabbour you're correct on both points.Sorry for the confusion! I'll approve this PR and I've opened https://github.com/Azure/helm-charts/issues/104 to add the AKS supporting information.

Thanks!

**Pull request merged**
