### PR TITLE
Add Magento chart

### PR DESCRIPTION
**Pull request by sabbour**
Created a chart for Magento that uses the OSBA Service Broker for MySQL.

This needs the latest PR for OSBA (https://github.com/Azure/open-service-broker-azure/pull/222) to be merged in order to work properly.

I think disk access is quite slow however, it takes about 25 minutes to get it up and running. Worth investigating.

### CODE REVIEW

**Comment by krancour** [comment]
I see that [this PR](https://github.com/kubernetes/charts/pull/3300) was just recently merged upstream. It adds support for using an external DB.

Since using Azure Database for MySQL is just a specific variation on the theme of "an external DB," I'd like to see this PR reconciled with the very latest from upstream where "external DB" is supported. By "reconciled," what I mean is that I'd like to see the differences between this chart and upstream minimized down to the very few that are meaningful. I recently did the same for our Wordpress chart (and some of our other charts need the same treatment as well, tbh).

I don't mind helping out with this myself if you want, since I've been through this a few times before.

**Comment by sabbour** [comment]
@krancour Sure, please go ahead. I'd rather learn how you did it the first time then apply to further charts. I'm also happy to do it if you point out the steps you've done from your previous experience.

**Comment by krancour** [comment]
@sabbour I'll give you an example of the sort of thing that need to be reconciled.

In this chart, we're (currently) using `mysql.embeddedMaria` (set to `true`) to indicate that the OSBA-provisioned MySQL should be ignored and an in-cluster MariaDB should be used instead. (I'm sure you adopted this pattern from looking at some of our other charts.)

In the meantime, the upstream Magento chart added support for external DBs, and they use `mariadb.enabled` (set to true) as the lever instead.

We should be more like them (to minimize the maintenance nightmare that could occur otherwise). i.e. We should decide on OSBA-provisioned MySQL or in-cluster MariaDB on the basis of `mariadb.enabled`, just like they do. The meaningful difference here, would simply be what the default value is.

Following this theme...

Currently (again, I know you copied it from other charts of ours) we have a `mysql.azure` section in `values.yaml`. Upstream, in the meantime, they've added an `externalDatabase` section. Again, acknowledging that using an OSBA-provisioned MySQL is just a special, narrow case of an external DB, I believe we should get rid of our `mysql` section, replace it with their `externalDatabase` section, kill off the params we don't care about in that section (we don't want to support external databases that _aren't_ Azure / aren't provisioned through OSBA). We can add an `externalDatabase.azure` section that covers what was once in `mysql.azure`.

My process for reconciling this involve diffing this PR against the latest from upstream an meticulously minimizing those diffs until the very few that are left are justifiable and unavoidable.

Sorry-- I know this sounds painstaking, and it can be, but I think it's worth it for the sake of avoiding a scenario where it becomes difficult to identify and pull in future changes from upstream.

**Comment by krancour** [comment]
I'm going to run through this quickly and amend this PR.

**Comment by krancour** [comment]
Reconciled. This still needs to be tested on all of the following:

- Minikube
  - OSBA-provisioned Azure Database for MySQL
  - Embedded MariaDB
- AKS
  - OSBA-provisioned Azure Database for MySQL
  - Embedded MariaDB

I'll try to cycle through those tonight and/or tomorrow.

**Comment by sabbour** [comment]
@krancour Is there an automated test process to do this next time?

**Comment by krancour** [comment]
@sabbour there isn't. Truth be told, we're not keen on there being to many "next times." We don't want to maintain a large repository of forked charts, because that can become a huge maintenance burden. (We're actually going through and deprioritizing a lot of the new chart / help wanted issues.)

What we're mainly interested in at this point are charts that test new / specific services that OSBA can provision. The magento chart proved to be interesting because it exposed that the permissions granted on bind to MySQL were wrong-- so we'll take this. Generally speaking, however, we don't expect to be adding new charts to this repo very frequently.

**Comment by sabbour** [comment]
@krancour It makes perfect sense as a test-bed/example repository. I agree.

**Comment by seanmck** [comment]
Repo is no longer maintained and is being archived.

**Pull request closed without merging**
